local compiler = loadstring or load
assert(type(compiler) == "function", "Rere requires loadstring or load")

local source = game:HttpGet("https://raw.githubusercontent.com/x8lua/Rere/v0.1.21/src/Rere.lua")
local Rere = assert(compiler(source))()
Rere.Init()

local enabled = Rere.State(true)
local speed = Rere.State(50)
local smoothness = Rere.State(0.5)
local playerName = Rere.State("")
local status = Rere.State("Ready")
local counter = Rere.State(0)
local theme = Rere.State("Dark")
local quality = Rere.State("High")
local region = Rere.State("North America")

Rere:Connect(function()
    Rere.Window({ "Rere Feature Demo" })
        Rere.TabBar()
            Rere.Tab({ "Dashboard" })
                Rere.Text({ "Runtime dashboard" })
                Rere.Separator()
                Rere.Text({ "Player: " .. game.Players.LocalPlayer.Name })
                Rere.Text({ "Place ID: " .. tostring(game.PlaceId) })
                Rere.Text({ "Status: " .. status:get() })
                Rere.CollapsingHeader({ "Help" })
                    Rere.Text({ "Use the sections below to explore Rere features." })
                Rere.End()
                Rere.CollapsingHeader({ "Configuration" })
                    Rere.Text({ "Adjust runtime values from the Controls tab." })
                Rere.End()
                Rere.CollapsingHeader({ "Window options" })
                    Rere.Text({ "Windows support dragging, resizing, and collapsing." })
                Rere.End()
                Rere.CollapsingHeader({ "Widgets" })
                    Rere.Text({ "Buttons, sliders, inputs, combos, and tabs are available." })
                Rere.End()
                Rere.CollapsingHeader({ "Popups & child windows" })
                    Rere.Text({ "Popup and child-window examples can be added here." })
                Rere.End()
                Rere.CollapsingHeader({ "Tables & columns" })
                    Rere.Text({ "Table and column widgets are supported by the library." })
                Rere.End()
                Rere.SeparatorText({ "Counter" })
                Rere.Text({ "Current value: " .. counter:get() })
                Rere.SameLine()
                    if Rere.Button({ "Decrease" }).clicked() then
                        counter:set(counter:get() - 1)
                    end
                    if Rere.Button({ "Increase" }).clicked() then
                        counter:set(counter:get() + 1)
                    end
                Rere.End()
            Rere.End()

            Rere.Tab({ "Controls" })
                Rere.Checkbox({ "Enabled" }, { isChecked = enabled })
                Rere.SliderNum({ "Speed", 1, 0, 100, "%d%%" }, { number = speed })
                Rere.DragNum({ "Smoothness", 0.01, 0, 1, "%.2f" }, { number = smoothness })
                Rere.InputText({ "Target player", "Enter a username..." }, { text = playerName })
                Rere.Separator()
                if Rere.Button({ "Apply settings" }).clicked() then
                    status:set(string.format("Applied: speed %d / smoothness %.2f", speed:get(), smoothness:get()))
                end
                Rere.SameLine()
                    if Rere.Button({ "Reset" }).clicked() then
                        enabled:set(true)
                        speed:set(50)
                        smoothness:set(0.5)
                        playerName:set("")
                        status:set("Reset complete")
                    end
                Rere.End()
            Rere.End()

            Rere.Tab({ "Dropdowns" })
                Rere.Text({ "Three dropdowns on one page" })
                Rere.ComboArray({ "Theme" }, { index = theme }, { "Dark", "Light", "System" })
                Rere.ComboArray({ "Quality" }, { index = quality }, { "Low", "Medium", "High" })
                Rere.ComboArray({ "Region" }, { index = region }, { "North America", "Europe", "Asia" })
            Rere.End()

            Rere.Tab({ "About" })
                Rere.Text({ "Rere v" .. Rere:GetVersion() })
                Rere.Text({ "Executor-compatible Iris build." })
                Rere.Text({ "Tabs are pages; ComboArray creates dropdowns." })
            Rere.End()
        Rere.End()
    Rere.End()
end)
